name: Update Readme

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Run script to update README
        run: npm run update-readme

      - name: Commit and push changes
        run: |
          git config user.name "dprakash2101"
          git config user.email "${{secrets.EMAIL}}"
          git add README.md
          if git diff --quiet; then
            echo "No changes in README. Skipping update."
            echo "::set-output name=changes::false"
          else
            echo "README has changes. Proceeding with update."
            echo "::set-output name=changes::true"
            git add README.md
            git commit -m "Update README"
            git push
          fi
        